import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "de" | "en" | "es";

type Dict = Record<string, string>;

const translations: Record<Language, Dict> = {
  de: {
    // Nav / Auth
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.shop": "Shop",
    "nav.reviews": "Bewertungen",
    "nav.about": "Über uns",
    "nav.surveys": "Studien",
    "nav.contact": "Kontakt",
    "auth.login": "Login",
    "auth.register": "Registrieren",
    "mode.motorcycle": "Motorrad",
    "mode.ski": "Ski",

    // Cart
    "cart.title": "Warenkorb",
    "cart.empty": "Dein Warenkorb ist leer.",
    "cart.total": "Gesamt",
    "cart.checkout": "Zur Kasse",
    "cart.added": "Zum Warenkorb hinzugefügt",
    "cart.addedDesc": "wurde hinzugefügt.",

    // Shop
    "shop.title": "Shop",
    "shop.subtitle": "Entdecke das SmartHelm Rücklicht und passendes Zubehör.",
    "shop.add": "In den Warenkorb",
    "shop.bestseller": "Bestseller",
    "product.1.name": "SmartHelm Rücklicht",
    "product.1.desc": "Das intelligente Helmrücklicht mit automatischer Bremserkennung, Erschütterungssensor und GPS-Tracking.",
    "product.2.name": "Universal-Halterung",
    "product.2.desc": "Passend für alle gängigen Motorrad- und Skihelme. Werkzeuglose Montage.",
    "product.3.name": "USB-C Ladekabel (2m)",
    "product.3.desc": "Hochwertiges Ladekabel für dein SmartHelm Rücklicht.",
    "product.4.name": "Ersatz-Akku Pack",
    "product.4.desc": "Zusätzlicher Akku für längere Touren und Ausflüge.",

    // Landing
    "landing.badge.motorcycle": "Motorrad-Modus",
    "landing.badge.ski": "Ski-Modus",
    "landing.hero.title1": "Sicherheit,",
    "landing.hero.title2": "die mitdenkt.",
    "landing.hero.desc.motorcycle": "Intelligentes Helmrücklicht mit automatischer Bremserkennung, Erschütterungssensor und GPS-Tracking für Motorradfahrer.",
    "landing.hero.desc.ski": "Smarter Schutz auf der Piste – erkennt Bremsungen, Stürze und zeichnet deine Abfahrten auf.",
    "landing.cta.buy": "Jetzt kaufen",
    "landing.cta.more": "Mehr erfahren",
    "landing.stats.users": "Nutzer",
    "landing.stats.rides": "Fahrten",
    "landing.stats.detection": "Erkennung",
    "landing.stats.reaction": "Reaktion",
    "landing.features.title1": "Was",
    "landing.features.title2": "kann",
    "landing.features.subtitle": "Vier Kernfunktionen für deine Sicherheit – intelligent, automatisch, zuverlässig.",
    "feature.brake.title": "Bremslicht",
    "feature.brake.desc": "Automatische Aktivierung bei Bremsung – für maximale Sichtbarkeit.",
    "feature.shock.title": "Erschütterung",
    "feature.shock.desc": "Erkennt Stürze und Unfälle in Echtzeit durch Sensorik.",
    "feature.gps.title": "GPS Tracking",
    "feature.gps.desc": "Zeichne deine Routen auf und analysiere dein Fahrverhalten.",
    "feature.smart.title": "Smart Features",
    "feature.smart.desc": "Arduino Nano 33 mit Beschleunigungs- und Bewegungssensoren.",
    "landing.how.title": "So funktioniert's",
    "landing.how.desc.motorcycle": "Bremslicht aktiviert sich automatisch bei starker Bremsung. Erschütterungserkennung bei Unfällen.",
    "landing.how.desc.ski": "Bremslicht aktiviert sich bei starker Bremsung UND Stillstand. Erschütterungserkennung bei Stürzen.",
    "landing.step1.title": "Montieren",
    "landing.step1.desc": "Rücklicht einfach am Helm befestigen. Passt auf jeden Helm.",
    "landing.step2.title": "Verbinden",
    "landing.step2.desc": "Per App koppeln und Modus wählen – Motorrad oder Ski.",
    "landing.step3.title": "Losfahren",
    "landing.step3.desc": "Das System erkennt automatisch Bremsungen und Erschütterungen.",
    "landing.reviews.title": "Was unsere Nutzer sagen",
    "landing.reviews.all": "Alle Bewertungen ansehen",
    "landing.cta.title": "Bereit für mehr Sicherheit?",
    "landing.cta.desc": "Hol dir jetzt das SmartHelm Rücklicht und fahre sicherer – auf der Straße und auf der Piste.",
    "landing.cta.order": "Jetzt bestellen",

    // Reviews
    "reviews.title": "Kundenbewertungen",
    "reviews.count": "Bewertungen",
    "reviews.filter.all": "Alle",
    "reviews.filter.motorcycle": "Motorrad",
    "reviews.filter.ski": "Ski",

    // About
    "about.title1": "Über",
    "about.subtitle": "Drei junge Unternehmer mit einer Mission: Sicherheit neu denken.",
    "about.story.title": "Unsere Geschichte",
    "about.story.p1": "Alles begann mit einer einfachen Frage: Warum gibt es kein intelligentes Rücklicht für Helme? Nach einem Beinahe-Unfall auf dem Motorrad war klar – hier fehlt etwas.",
    "about.story.p2": "Mit einem Arduino Nano 33, Beschleunigungssensoren und viel Leidenschaft entstand das SmartHelm Rücklicht. Ein System, das automatisch erkennt, ob du bremst oder stürzt – und andere warnt.",
    "about.vision.label": "Unsere Vision:",
    "about.vision.text": "Jeder Helm wird smart. Jede Fahrt wird sicherer. Für Motorradfahrer und Skifahrer weltweit.",
    "about.role.tech": "Technik & Entwicklung",
    "about.role.design": "Design & Produkt",
    "about.role.business": "Business & Marketing",
    "about.motivation.tech": "Ich wollte Technologie schaffen, die Leben rettet – nicht nur Gadgets.",
    "about.motivation.design": "Sicherheit muss nicht langweilig aussehen. Gutes Design macht den Unterschied.",
    "about.motivation.business": "Jeder Fahrer verdient smarten Schutz – wir machen ihn zugänglich.",

    // Contact
    "contact.title1": "Kontakt &",
    "contact.title2": "Service",
    "contact.subtitle": "Fragen, Feedback oder Support? Wir sind für dich da.",
    "contact.success.title": "Vielen Dank!",
    "contact.success.desc": "Deine Nachricht wurde erfolgreich gesendet.",
    "contact.success.new": "Neue Nachricht",
    "contact.field.name": "Name",
    "contact.field.namePh": "Dein Name",
    "contact.field.email": "E-Mail",
    "contact.field.category": "Kategorie",
    "contact.field.categoryPh": "Wähle eine Kategorie",
    "contact.cat.general": "Allgemeine Anfrage",
    "contact.cat.support": "Support",
    "contact.cat.complaint": "Reklamation",
    "contact.cat.partnership": "Kooperation",
    "contact.field.message": "Nachricht",
    "contact.field.messagePh": "Deine Nachricht...",
    "contact.send": "Nachricht senden",
    "contact.toast.title": "Nachricht gesendet!",
    "contact.toast.desc": "Wir melden uns in Kürze bei dir.",
    "contact.direct": "Oder direkt an:",

    // Surveys
    "surveys.title1": "Studien &",
    "surveys.title2": "Statistiken",
    "surveys.subtitle": "Daten und Fakten zu Verkehrs- und Skiunfällen – warum smarte Sicherheit wichtig ist.",
    "surveys.chart1": "Unfallzahlen pro Jahr (DE)",
    "surveys.chart2": "Unfallursachen",
    "surveys.cause.visibility": "Mangelnde Sichtbarkeit",
    "surveys.cause.brake": "Zu spät gebremst",
    "surveys.cause.shock": "Erschütterung/Sturz",
    "surveys.cause.other": "Sonstige",
    "surveys.insight": "der Unfälle mit Motorrädern und Skifahrern könnten durch bessere Sichtbarkeit und schnellere Bremserkennung verhindert oder gemildert werden.",

    // Dashboard
    "dash.login.title": "Dashboard Login",
    "dash.login.desc": "Melde dich an, um deine Fahrdaten und Statistiken zu sehen.",
    "dash.login.button": "Demo-Login starten",
    "dash.title1": "Mein",
    "dash.title2": "Dashboard",
    "dash.lastTrip": "Letzte Fahrt: Heute, 14:35",
    "dash.export": "GPX Export",
    "dash.stat.speed": "Ø Geschwindigkeit",
    "dash.stat.speedSub": "+3% vs. letzte Fahrt",
    "dash.stat.distance": "Gefahrene Strecke",
    "dash.stat.distanceSub": "Heute",
    "dash.stat.brakes": "Bremsungen",
    "dash.stat.brakesSub": "3 stark",
    "dash.stat.shocks": "Erschütterungen",
    "dash.stat.shocksSub": "Leicht",
    "dash.map": "Kartenansicht",
    "dash.legend.start": "Start",
    "dash.legend.brake": "Bremsung",
    "dash.legend.shock": "Erschütterung",
    "dash.legend.end": "Ziel",
    "dash.speed": "Geschwindigkeit & Beschleunigung",
    "dash.brakeBehavior": "Bremsverhalten",
    "dash.brake.light": "Leichte Bremsungen",
    "dash.brake.strong": "Starke Bremsungen",
    "dash.brake.emergency": "Notbremsungen",
    "dash.timeline": "Ereignis-Timeline",
    "dash.event.start": "Fahrt gestartet",
    "dash.event.brake1": "Starke Bremsung erkannt",
    "dash.event.brake2": "Bremsung bei Kurve",
    "dash.event.shock": "Erschütterung erkannt",
    "dash.event.brake3": "Bremsung vor Kreuzung",
    "dash.event.end": "Fahrt beendet",

    // Footer
    "footer.tagline": "Sicherheit, die mitdenkt. Intelligentes Helmrücklicht für Motorrad & Ski.",
    "footer.company": "Unternehmen",
    "footer.legal": "Rechtliches",
    "footer.social": "Social Media",
    "footer.impressum": "Impressum",
    "footer.privacy": "Datenschutz",
    "footer.agb": "AGB",
    "footer.rights": "Alle Rechte vorbehalten.",

    // 404
    "nf.title": "Hoppla! Seite nicht gefunden",
    "nf.back": "Zurück zur Startseite",
  },
  en: {
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.shop": "Shop",
    "nav.reviews": "Reviews",
    "nav.about": "About",
    "nav.surveys": "Studies",
    "nav.contact": "Contact",
    "auth.login": "Login",
    "auth.register": "Sign up",
    "mode.motorcycle": "Motorcycle",
    "mode.ski": "Ski",

    "cart.title": "Cart",
    "cart.empty": "Your cart is empty.",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "cart.added": "Added to cart",
    "cart.addedDesc": "was added.",

    "shop.title": "Shop",
    "shop.subtitle": "Discover the SmartHelm taillight and matching accessories.",
    "shop.add": "Add to cart",
    "shop.bestseller": "Bestseller",
    "product.1.name": "SmartHelm Taillight",
    "product.1.desc": "The intelligent helmet taillight with automatic brake detection, shock sensor and GPS tracking.",
    "product.2.name": "Universal Mount",
    "product.2.desc": "Fits all common motorcycle and ski helmets. Tool-free installation.",
    "product.3.name": "USB-C Charging Cable (2m)",
    "product.3.desc": "High-quality charging cable for your SmartHelm taillight.",
    "product.4.name": "Spare Battery Pack",
    "product.4.desc": "Extra battery for longer tours and trips.",

    "landing.badge.motorcycle": "Motorcycle Mode",
    "landing.badge.ski": "Ski Mode",
    "landing.hero.title1": "Safety",
    "landing.hero.title2": "that thinks ahead.",
    "landing.hero.desc.motorcycle": "Intelligent helmet taillight with automatic brake detection, shock sensor and GPS tracking for motorcyclists.",
    "landing.hero.desc.ski": "Smart protection on the slope – detects braking, falls and records your runs.",
    "landing.cta.buy": "Buy now",
    "landing.cta.more": "Learn more",
    "landing.stats.users": "Users",
    "landing.stats.rides": "Rides",
    "landing.stats.detection": "Detection",
    "landing.stats.reaction": "Reaction",
    "landing.features.title1": "What",
    "landing.features.title2": "can do",
    "landing.features.subtitle": "Four core functions for your safety – intelligent, automatic, reliable.",
    "feature.brake.title": "Brake Light",
    "feature.brake.desc": "Automatic activation when braking – for maximum visibility.",
    "feature.shock.title": "Shock",
    "feature.shock.desc": "Detects falls and accidents in real time through sensors.",
    "feature.gps.title": "GPS Tracking",
    "feature.gps.desc": "Record your routes and analyze your riding behavior.",
    "feature.smart.title": "Smart Features",
    "feature.smart.desc": "Arduino Nano 33 with acceleration and motion sensors.",
    "landing.how.title": "How it works",
    "landing.how.desc.motorcycle": "Brake light activates automatically on hard braking. Shock detection on accidents.",
    "landing.how.desc.ski": "Brake light activates on hard braking AND standstill. Shock detection on falls.",
    "landing.step1.title": "Mount",
    "landing.step1.desc": "Simply attach the taillight to the helmet. Fits every helmet.",
    "landing.step2.title": "Connect",
    "landing.step2.desc": "Pair via app and choose mode – motorcycle or ski.",
    "landing.step3.title": "Ride",
    "landing.step3.desc": "The system automatically detects braking and shocks.",
    "landing.reviews.title": "What our users say",
    "landing.reviews.all": "View all reviews",
    "landing.cta.title": "Ready for more safety?",
    "landing.cta.desc": "Get the SmartHelm taillight now and ride safer – on the road and on the slope.",
    "landing.cta.order": "Order now",

    "reviews.title": "Customer Reviews",
    "reviews.count": "reviews",
    "reviews.filter.all": "All",
    "reviews.filter.motorcycle": "Motorcycle",
    "reviews.filter.ski": "Ski",

    "about.title1": "About",
    "about.subtitle": "Three young entrepreneurs with one mission: rethinking safety.",
    "about.story.title": "Our Story",
    "about.story.p1": "It all started with a simple question: Why isn't there an intelligent taillight for helmets? After a near-accident on the motorcycle, it was clear – something is missing.",
    "about.story.p2": "With an Arduino Nano 33, accelerometers and a lot of passion, the SmartHelm taillight was born. A system that automatically detects whether you brake or fall – and warns others.",
    "about.vision.label": "Our Vision:",
    "about.vision.text": "Every helmet becomes smart. Every ride becomes safer. For motorcyclists and skiers worldwide.",
    "about.role.tech": "Tech & Development",
    "about.role.design": "Design & Product",
    "about.role.business": "Business & Marketing",
    "about.motivation.tech": "I wanted to build technology that saves lives – not just gadgets.",
    "about.motivation.design": "Safety doesn't have to look boring. Good design makes the difference.",
    "about.motivation.business": "Every rider deserves smart protection – we make it accessible.",

    "contact.title1": "Contact &",
    "contact.title2": "Service",
    "contact.subtitle": "Questions, feedback or support? We're here for you.",
    "contact.success.title": "Thank you!",
    "contact.success.desc": "Your message has been sent successfully.",
    "contact.success.new": "New message",
    "contact.field.name": "Name",
    "contact.field.namePh": "Your name",
    "contact.field.email": "Email",
    "contact.field.category": "Category",
    "contact.field.categoryPh": "Choose a category",
    "contact.cat.general": "General inquiry",
    "contact.cat.support": "Support",
    "contact.cat.complaint": "Complaint",
    "contact.cat.partnership": "Partnership",
    "contact.field.message": "Message",
    "contact.field.messagePh": "Your message...",
    "contact.send": "Send message",
    "contact.toast.title": "Message sent!",
    "contact.toast.desc": "We will get back to you shortly.",
    "contact.direct": "Or directly at:",

    "surveys.title1": "Studies &",
    "surveys.title2": "Statistics",
    "surveys.subtitle": "Data and facts about traffic and ski accidents – why smart safety matters.",
    "surveys.chart1": "Accidents per year (DE)",
    "surveys.chart2": "Accident causes",
    "surveys.cause.visibility": "Lack of visibility",
    "surveys.cause.brake": "Braked too late",
    "surveys.cause.shock": "Shock/Fall",
    "surveys.cause.other": "Other",
    "surveys.insight": "of motorcycle and ski accidents could be prevented or mitigated through better visibility and faster brake detection.",

    "dash.login.title": "Dashboard Login",
    "dash.login.desc": "Log in to see your ride data and statistics.",
    "dash.login.button": "Start demo login",
    "dash.title1": "My",
    "dash.title2": "Dashboard",
    "dash.lastTrip": "Last ride: Today, 14:35",
    "dash.export": "GPX Export",
    "dash.stat.speed": "Avg. Speed",
    "dash.stat.speedSub": "+3% vs. last ride",
    "dash.stat.distance": "Distance",
    "dash.stat.distanceSub": "Today",
    "dash.stat.brakes": "Brakings",
    "dash.stat.brakesSub": "3 hard",
    "dash.stat.shocks": "Shocks",
    "dash.stat.shocksSub": "Light",
    "dash.map": "Map view",
    "dash.legend.start": "Start",
    "dash.legend.brake": "Braking",
    "dash.legend.shock": "Shock",
    "dash.legend.end": "End",
    "dash.speed": "Speed & Acceleration",
    "dash.brakeBehavior": "Brake behavior",
    "dash.brake.light": "Light brakings",
    "dash.brake.strong": "Hard brakings",
    "dash.brake.emergency": "Emergency brakings",
    "dash.timeline": "Event Timeline",
    "dash.event.start": "Ride started",
    "dash.event.brake1": "Hard braking detected",
    "dash.event.brake2": "Braking in curve",
    "dash.event.shock": "Shock detected",
    "dash.event.brake3": "Braking before junction",
    "dash.event.end": "Ride ended",

    "footer.tagline": "Safety that thinks ahead. Intelligent helmet taillight for motorcycle & ski.",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.social": "Social Media",
    "footer.impressum": "Imprint",
    "footer.privacy": "Privacy",
    "footer.agb": "Terms",
    "footer.rights": "All rights reserved.",

    "nf.title": "Oops! Page not found",
    "nf.back": "Return to Home",
  },
  es: {
    "nav.home": "Inicio",
    "nav.dashboard": "Panel",
    "nav.shop": "Tienda",
    "nav.reviews": "Reseñas",
    "nav.about": "Sobre nosotros",
    "nav.surveys": "Estudios",
    "nav.contact": "Contacto",
    "auth.login": "Acceder",
    "auth.register": "Registrarse",
    "mode.motorcycle": "Motocicleta",
    "mode.ski": "Esquí",

    "cart.title": "Carrito",
    "cart.empty": "Tu carrito está vacío.",
    "cart.total": "Total",
    "cart.checkout": "Pagar",
    "cart.added": "Añadido al carrito",
    "cart.addedDesc": "fue añadido.",

    "shop.title": "Tienda",
    "shop.subtitle": "Descubre la luz trasera SmartHelm y los accesorios.",
    "shop.add": "Añadir al carrito",
    "shop.bestseller": "Más vendido",
    "product.1.name": "Luz trasera SmartHelm",
    "product.1.desc": "La luz trasera inteligente para casco con detección automática de frenado, sensor de impactos y GPS.",
    "product.2.name": "Soporte universal",
    "product.2.desc": "Compatible con todos los cascos de moto y esquí. Montaje sin herramientas.",
    "product.3.name": "Cable de carga USB-C (2m)",
    "product.3.desc": "Cable de carga de alta calidad para tu luz trasera SmartHelm.",
    "product.4.name": "Pack de batería de repuesto",
    "product.4.desc": "Batería adicional para tours y excursiones más largas.",

    "landing.badge.motorcycle": "Modo Moto",
    "landing.badge.ski": "Modo Esquí",
    "landing.hero.title1": "Seguridad",
    "landing.hero.title2": "que se anticipa.",
    "landing.hero.desc.motorcycle": "Luz trasera de casco inteligente con detección automática de frenado, sensor de impactos y GPS para motociclistas.",
    "landing.hero.desc.ski": "Protección inteligente en la pista: detecta frenadas, caídas y registra tus descensos.",
    "landing.cta.buy": "Comprar ahora",
    "landing.cta.more": "Saber más",
    "landing.stats.users": "Usuarios",
    "landing.stats.rides": "Recorridos",
    "landing.stats.detection": "Detección",
    "landing.stats.reaction": "Reacción",
    "landing.features.title1": "Qué hace",
    "landing.features.title2": "",
    "landing.features.subtitle": "Cuatro funciones clave para tu seguridad: inteligente, automática, fiable.",
    "feature.brake.title": "Luz de freno",
    "feature.brake.desc": "Activación automática al frenar para máxima visibilidad.",
    "feature.shock.title": "Impacto",
    "feature.shock.desc": "Detecta caídas y accidentes en tiempo real mediante sensores.",
    "feature.gps.title": "GPS",
    "feature.gps.desc": "Graba tus rutas y analiza tu conducción.",
    "feature.smart.title": "Funciones inteligentes",
    "feature.smart.desc": "Arduino Nano 33 con sensores de aceleración y movimiento.",
    "landing.how.title": "Cómo funciona",
    "landing.how.desc.motorcycle": "La luz de freno se activa automáticamente al frenar fuerte. Detección de impactos en accidentes.",
    "landing.how.desc.ski": "La luz se activa al frenar fuerte Y al detenerse. Detección de impactos en caídas.",
    "landing.step1.title": "Montar",
    "landing.step1.desc": "Fija fácilmente la luz al casco. Compatible con cualquier casco.",
    "landing.step2.title": "Conectar",
    "landing.step2.desc": "Empareja con la app y elige el modo: moto o esquí.",
    "landing.step3.title": "Conducir",
    "landing.step3.desc": "El sistema detecta automáticamente frenadas e impactos.",
    "landing.reviews.title": "Lo que dicen nuestros usuarios",
    "landing.reviews.all": "Ver todas las reseñas",
    "landing.cta.title": "¿Listo para más seguridad?",
    "landing.cta.desc": "Hazte ya con la luz trasera SmartHelm y conduce más seguro, en carretera y en la pista.",
    "landing.cta.order": "Pedir ahora",

    "reviews.title": "Reseñas de clientes",
    "reviews.count": "reseñas",
    "reviews.filter.all": "Todas",
    "reviews.filter.motorcycle": "Moto",
    "reviews.filter.ski": "Esquí",

    "about.title1": "Sobre",
    "about.subtitle": "Tres jóvenes emprendedores con una misión: repensar la seguridad.",
    "about.story.title": "Nuestra historia",
    "about.story.p1": "Todo empezó con una pregunta sencilla: ¿por qué no existe una luz trasera inteligente para cascos? Tras un casi accidente en moto, quedó claro: faltaba algo.",
    "about.story.p2": "Con un Arduino Nano 33, acelerómetros y mucha pasión nació la luz trasera SmartHelm. Un sistema que detecta automáticamente si frenas o caes y avisa a los demás.",
    "about.vision.label": "Nuestra visión:",
    "about.vision.text": "Cada casco se vuelve inteligente. Cada viaje, más seguro. Para motociclistas y esquiadores de todo el mundo.",
    "about.role.tech": "Tecnología y desarrollo",
    "about.role.design": "Diseño y producto",
    "about.role.business": "Negocio y marketing",
    "about.motivation.tech": "Quería crear tecnología que salve vidas, no solo gadgets.",
    "about.motivation.design": "La seguridad no tiene que ser aburrida. El buen diseño marca la diferencia.",
    "about.motivation.business": "Cada conductor merece protección inteligente; la hacemos accesible.",

    "contact.title1": "Contacto y",
    "contact.title2": "Servicio",
    "contact.subtitle": "¿Preguntas, comentarios o soporte? Estamos aquí.",
    "contact.success.title": "¡Gracias!",
    "contact.success.desc": "Tu mensaje se ha enviado correctamente.",
    "contact.success.new": "Nuevo mensaje",
    "contact.field.name": "Nombre",
    "contact.field.namePh": "Tu nombre",
    "contact.field.email": "Correo",
    "contact.field.category": "Categoría",
    "contact.field.categoryPh": "Elige una categoría",
    "contact.cat.general": "Consulta general",
    "contact.cat.support": "Soporte",
    "contact.cat.complaint": "Reclamación",
    "contact.cat.partnership": "Cooperación",
    "contact.field.message": "Mensaje",
    "contact.field.messagePh": "Tu mensaje...",
    "contact.send": "Enviar mensaje",
    "contact.toast.title": "¡Mensaje enviado!",
    "contact.toast.desc": "Te contactaremos en breve.",
    "contact.direct": "O directamente a:",

    "surveys.title1": "Estudios y",
    "surveys.title2": "Estadísticas",
    "surveys.subtitle": "Datos y hechos sobre accidentes de tráfico y esquí: por qué la seguridad inteligente importa.",
    "surveys.chart1": "Accidentes por año (DE)",
    "surveys.chart2": "Causas de accidentes",
    "surveys.cause.visibility": "Falta de visibilidad",
    "surveys.cause.brake": "Frenado tardío",
    "surveys.cause.shock": "Impacto/Caída",
    "surveys.cause.other": "Otros",
    "surveys.insight": "de los accidentes de moto y esquí podrían evitarse o mitigarse con mejor visibilidad y detección de frenado más rápida.",

    "dash.login.title": "Acceso al panel",
    "dash.login.desc": "Inicia sesión para ver tus datos y estadísticas.",
    "dash.login.button": "Iniciar demo",
    "dash.title1": "Mi",
    "dash.title2": "Panel",
    "dash.lastTrip": "Último viaje: Hoy, 14:35",
    "dash.export": "Exportar GPX",
    "dash.stat.speed": "Velocidad media",
    "dash.stat.speedSub": "+3% vs. último viaje",
    "dash.stat.distance": "Distancia",
    "dash.stat.distanceSub": "Hoy",
    "dash.stat.brakes": "Frenadas",
    "dash.stat.brakesSub": "3 fuertes",
    "dash.stat.shocks": "Impactos",
    "dash.stat.shocksSub": "Leve",
    "dash.map": "Mapa",
    "dash.legend.start": "Inicio",
    "dash.legend.brake": "Frenada",
    "dash.legend.shock": "Impacto",
    "dash.legend.end": "Fin",
    "dash.speed": "Velocidad y aceleración",
    "dash.brakeBehavior": "Comportamiento de frenado",
    "dash.brake.light": "Frenadas suaves",
    "dash.brake.strong": "Frenadas fuertes",
    "dash.brake.emergency": "Frenadas de emergencia",
    "dash.timeline": "Cronología de eventos",
    "dash.event.start": "Viaje iniciado",
    "dash.event.brake1": "Frenada fuerte detectada",
    "dash.event.brake2": "Frenada en curva",
    "dash.event.shock": "Impacto detectado",
    "dash.event.brake3": "Frenada antes del cruce",
    "dash.event.end": "Viaje finalizado",

    "footer.tagline": "Seguridad que se anticipa. Luz trasera inteligente para moto y esquí.",
    "footer.company": "Empresa",
    "footer.legal": "Legal",
    "footer.social": "Redes sociales",
    "footer.impressum": "Aviso legal",
    "footer.privacy": "Privacidad",
    "footer.agb": "Términos",
    "footer.rights": "Todos los derechos reservados.",

    "nf.title": "¡Ups! Página no encontrada",
    "nf.back": "Volver al inicio",
  },
};

interface LangCtx {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LangCtx>({ lang: "de", setLang: () => {}, t: (k) => k });

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("lang");
    return (saved as Language) || "de";
  });

  useEffect(() => {
    document.documentElement.lang = lang;
    localStorage.setItem("lang", lang);
  }, [lang]);

  const t = (key: string) => translations[lang][key] || translations.de[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: setLangState, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
